name: salingsapa
description: A Final Exam Project
publish_to: 'none'

version: 0.14.2+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  firebase_core: ^3.9.0
  firebase_analytics: ^11.3.6
  firebase_auth: ^5.3.4
  firebase_messaging: ^15.1.6
  firebase_remote_config: ^5.2.0
  cloud_firestore: ^5.6.0
  firebase_app_check: ^0.3.1+7
  get_it: ^8.0.3
  flutter_local_notifications: ^18.0.1
  rxdart: ^0.28.0
  json_annotation: ^4.8.0
  flutter_secure_storage: ^9.0.0
  freezed: ^2.3.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  dynamic_color: ^1.6.2
  flutter_contacts: ^1.1.6
  permission_handler: ^11.0.1
  agora_rtc_engine: ^6.5.0
  uuid: ^4.1.0
  firebase_storage: ^12.3.7
  image_picker: ^1.0.4
  cached_network_image: ^3.2.3
  flutter_ringtone_player: ^4.0.0+2
  http: ^1.1.0
  camera: ^0.11.0
  speech_to_text: ^7.0.0
  tflite:
    git:
      url: https://github.com/baharudin-yusup/flutter_tflite
      ref: master
  path_provider: ^2.1.2
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  flutter_markdown: ^0.7.1
  modal_bottom_sheet: ^3.0.0-pre
  url_launcher: ^6.2.4
  envied: ^1.0.0
  country_codes: ^3.1.0+2
  flutter_libphonenumber: ^2.2.2
  shared_preferences: ^2.2.3
  fl_country_code_picker: ^0.1.9+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.10
  json_serializable: ^6.6.1
  envied_generator: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/sign_language_recognition/
