name: salingsapa
description: A Final Exam Project
publish_to: 'none'

version: 0.5.0+3

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  firebase_core: ^2.5.0
  firebase_analytics: ^10.1.1
  firebase_auth: ^4.2.6
  firebase_messaging: ^14.2.2
  firebase_remote_config: ^4.2.2
  cloud_firestore: ^4.3.2
  firebase_app_check: ^0.2.0+1
  get_it: ^7.2.0
  flutter_local_notifications: ^16.1.0

  rxdart: ^0.27.7
  json_annotation: ^4.8.0

  flutter_secure_storage: ^9.0.0
  freezed: ^2.3.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  flutter_native_splash: ^2.2.17
  dynamic_color: ^1.6.2
  contacts_service: ^0.6.3
  flutter_contacts: ^1.1.6
  permission_handler: ^11.0.1
  introduction_screen: ^3.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  agora_uikit: ^1.2.1
  agora_rtc_engine: ^6.2.6
  uuid: ^4.1.0
  firebase_storage: ^11.0.16
  image_picker: ^1.0.4
  cached_network_image: ^3.2.3
  flutter_ringtone_player: ^3.2.0
  http: ^1.1.0
  camera: ^0.10.5+2
  speech_to_text: ^6.1.1
  tflite: ^1.1.2
  path_provider: ^2.1.2
  dio: ^5.4.0
  fluttertoast: ^8.2.4

dependency_overrides:
  tflite:
    git:
      url: https://github.com/St-Luciferr/flutter_tflite.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/sign_language_recognition/
