// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfazNdjjuj3XnclxdyVhJdMueY-6fm_No',
    appId: '1:721041824886:android:02fa4f202301d0cd8a5357',
    messagingSenderId: '721041824886',
    projectId: 'salingsapa-project',
    storageBucket: 'salingsapa-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfqDip5zDNjPB7Zd6QUQ7QlDNT4ZtYRf0',
    appId: '1:721041824886:ios:0a0d51210d0a6fab8a5357',
    messagingSenderId: '721041824886',
    projectId: 'salingsapa-project',
    storageBucket: 'salingsapa-project.appspot.com',
    androidClientId: '721041824886-1otshq0alnsu8mr5cnrr7i01mklnfar6.apps.googleusercontent.com',
    iosClientId: '721041824886-liqqjh1q059utr84o2itv18h80c8ga2b.apps.googleusercontent.com',
    iosBundleId: 'dev.baharudin.salingsapa.dev',
  );
}
